language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - tools # https://github.com/travis-ci/travis-ci/issues/6059
    - platform-tools
    - android-25
    - build-tools-25.0.1
    - extra-android-support
before_script: cd $TRAVIS_BUILD_DIR/AndroidTestingBlueprint
script: ./gradlew app:connectedAndroidTest