language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - tools # https://github.com/travis-ci/travis-ci/issues/6059
    - platform-tools
    - android-25
    - build-tools-25.0.1
    - extra-android-support
    - extra-android-m2repository
before_script:
    - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
    - cd $TRAVIS_BUILD_DIR/AndroidTestingBlueprint
script: ./gradlew app:connectedAndroidTest